### PR TITLE
RFC: coproduct support

### PR DESCRIPTION
**Pull request by deepfire**
This lifts the `Code a ~ '[xs]` restriction -- hence adding support for coproducts.

This is mainly a request for comments -- there probably are very many possible improvements to make:

- [x] Went for `Traversal`. ~Choose a better name -- people say it's not a prism~
- [ ] This obviously adds duplication, so a factoring strategy needs to be decided.
- [ ] There is a bunch of excessive type signatures, to be removed.
- [ ] Suggestions?

### CODE REVIEW

**Comment by phadej** [comment]
Am I missing something, I don't see anything prism-y here. Yet?

**Comment by deepfire-pusher** [comment]
@phadej, there is no constraint on `Code a` to be `[xs]`, so this generates lens for co-products.

Frankly, I don't know what's the right term for this "thing" -- but I had the impression that prisms are partial lens.

**Comment by deepfire** [comment]
@phadej, there is no constraint on Code a to be [xs], so this generates lens for co-products -- which is the intent of this PR.

Frankly, I don't know what's the right term for this "thing" -- but I had the impression that prisms are partial lens.

**Comment by deepfire** [comment]
@phadej, to clarify -- if you have a better name, please do suggest, by any means!

**Comment by deepfire-pusher** [comment]
I'm thinking an alternative name could be ~"partial lens"~ Traversal.

Does that sound better?

**Comment by deepfire** [comment]
Renamed to Traversal.

**Comment by deepfire-pusher** [comment]
Cc @kosmikus.

It seems like this package is obsoleted by `optics`?  If so that makes this PR a bit pointless.

**Comment by edsko** [comment]
@deepfire-pusher given that this PR is many years old now (and given that I just modified this package..), I'm going to close this PR. If you still need this generalization, let me know.

**Pull request closed without merging**
